Models/ErrorViewModel.cs
namespace Avaliacao.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/LojasViewModel.cs
namespace Avaliacao.Models;

public class LojasViewModel
{
    public int Id { get; set; }
    public string Piso { get; set; }
    public string Nome { get; set; }
    public string Descricao { get; set; }
    public string Tipo { get; set; }
    public string Email { get; set; }

    public LojasViewModel(int id, string piso, string nome, string descricao, string tipo, string email)
    {
        this.Id = id;
        this.Piso = piso;
        this.Nome = nome;
        this.Descricao = descricao;
        this.Tipo = tipo;
        this.Email = email;
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Avaliacao.Models;

namespace Avaliacao.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LojasController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Avaliacao.Models;

namespace Avaliacao.Controllers;

public class LojasController : Controller {
    public static List<LojasViewModel> lojas = new List<LojasViewModel>();

    public IActionResult Index()
    {
        return View(lojas);
    }

    public IActionResult Gerenciamento()
    {
        return View(lojas);
    }

    public IActionResult Excluir(int id)
    {
        lojas.RemoveAt(id-1);
        return View();
    }

    public IActionResult Detalhe(int id)
    {
        return View(lojas[id-1]);
    }

    public IActionResult Cadastro([FromForm] string piso, [FromForm] string nome, [FromForm] string descricao, [FromForm] string tipo, [FromForm] string email)
    {
        int id = 1;

        foreach(var loja in lojas)
        {
            if(nome == loja.Nome) 
            {
                ViewData["Mensagem"] = "Não foi possivel completar o cadastro!";
                ViewData["Motivo"] = "Loja já cadastrada!";
                return View();
            }
        }

        for(int i = 0; i < lojas.Count; i++) {
            id++;
        }
       
        lojas.Add(new LojasViewModel(id, piso, nome, descricao, tipo, email));

        ViewData["Mensagem"] = "Cadastro completo!";
        ViewData["Motivo"] = "Loja cadastrada com sucesso!";
        return View();
    }
    
    public IActionResult Cadastrar()
    {
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Lojas/Cadastrar.cshtml
@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastramento</h1>

<form action="Cadastro" method="POST">

    <label for="piso">Piso: </label>
    <select name="piso" id="piso">
        <option value="Piso 1">1</option>
        <option value="Piso 2">2</option>
        <option value="Piso 3">3</option>
    </select>
    <br>

    <label for="nome">Nome: </label><br>
    <input type="text" id="nome" name="nome">
    <br>

    <label for="descricao">Descrição: </label><br>
    <input type="text" id="descricao" name="descricao">
    <br>

    <label for="tipo">Tipo: </label>    <br>
    <input type="text" id="tipo" name="tipo">
    <br>

    <label for="email">E-mail: </label><br>
    <input type="email" id="email" name="email">
    <br>

    <input type="submit" value="Cadastrar">
</form>

Views/Lojas/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}

<h1>@ViewData["Mensagem"]</h1>
<p>@ViewData["Motivo"]</p>

Views/Lojas/Detalhe.cshtml
@model Avaliacao.Models.LojasViewModel

@{
    ViewData["Title"] = "Detalhe";
}

<h1>@Model.Nome</h1>
<p>@Model.Id</p>
<p>@Model.Piso</p>
<p>@Model.Descricao</p>
<p>@Model.Email</p>

Views/Lojas/Excluir.cshtml
@{
    ViewData["Title"] = "Excluir";
}

<p>Loja excluida!</p>

Views/Lojas/Gerenciamento.cshtml
@model List<Avaliacao.Models.LojasViewModel>

@{
    ViewData["Title"] = "Gerenciamento";
}
    
<h1>Gerenciamento</h1>
    
@if(!(Model.Count == 0))
{
    <hr>
    @foreach(var loja in Model)
    {
    <h1>@loja.Nome</h1>
        <a href="Excluir/@loja.Id">Excluir</a>
        <a href="Detalhe/@loja.Id">Detalhe</a>
    <hr>
    }
}
else
{
    <p>Nenhum registro!</p>
}

Views/Lojas/Index.cshtml
@model List<Avaliacao.Models.LojasViewModel>

@{
    ViewData["Title"] = "Index";
}
    
<h1>Index</h1>
    
@if(!(Model.Count == 0))
{
    <hr>
    @foreach(var loja in Model)
    {
    <h1>@loja.Nome</h1>
    <hr>
    }
}
else
{
    <p>Nenhum registro!</p>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avaliacao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AvaliacaoLp3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Avaliacao</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Index">Lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Gerenciamento">Gerenciamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Cadastrar">Cadastro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AvaliacaoLp3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>